name = "ArnoTester"
uuid = "a147a8ac-57a7-43b1-b474-01d783569238"
authors = ["ArnoStrouwen <arno.strouwen@telenet.be> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
